/// <reference types="cypress" />

describe('Herokuapp testing', () => {
    it('Log in with valid data', () => {
   cy.intercept("/secure").as('login')
   cy.visit ("/login")
      .get ('[name="username"]')
      .type ('tomsmith')
      .get ('[name="password"]')
      .type ('SuperSecretPassword!')
      .get ('.fa.fa-2x.fa-sign-in').contains ('Login')
      .click()
      .wait('@login')
      .get ('.flash.success')
      .should ('contain', 'You logged into a secure area!')
    })
    it('Log in with invalid data', () => {
      cy.intercept("/login").as('login') 
      cy.visit ('/login')
        .get ('[name="username"]')
        .type ('invalidlogin')
        .get ('[name="password"]')
        .type ('invalidpassword')
        .get ('.fa.fa-2x.fa-sign-in').contains ('Login')
        .click()
        .wait('@login')
        .get ('.flash.error')
        .should ('contain', 'Your username is invalid!')
    })
    it('Succesfull logout', () => {
      cy.intercept("/secure").as('login')
      cy.visit ("/login")
        .get ('[name="username"]')
        .type ('tomsmith')
        .get ('[name="password"]')
        .type ('SuperSecretPassword!')
        .get ('.fa.fa-2x.fa-sign-in').contains ('Login')
        .click ()
        .wait ('@login')
        .get ('.icon-2x.icon-signout').contains ('Logout')
        .click ()
        .get('.flash.success')
        .should('contain', 'You logged out of the secure area!')
    })

  })